@startuml
!include .\\DAL\PrintOMaticContextFactory.puml
!include .\\DAL\PrintOMatic_Context.puml
!include .\\DTO\AccountDTO.puml
!include .\\DTO\ConversionDTO.puml
!include .\\DTO\GroupDTO.puml
!include .\\DTO\TransactionHistoryDTO.puml
!include .\\DTO\UserDTO.puml
!include .\\DTO\UserGroupDTO.puml
!include .\\MVC\Program.puml
!include .\\WebAPI\Program.puml
!include .\\DAL\Classes\Enums.puml
!include .\\DAL\Models\Account.puml
!include .\\DAL\Models\Conversion.puml
!include .\\DAL\Models\Group.puml
!include .\\DAL\Models\TransactionHistory.puml
!include .\\DAL\Models\User.puml
!include .\\DAL\Models\UserGroup.puml
!include .\\MVC\Controllers\AppUserController.puml
!include .\\MVC\Controllers\FacultiesController.puml
!include .\\MVC\Controllers\HomeController.puml
!include .\\MVC\Controllers\LoginController.puml
!include .\\MVC\Models\AppUserBuyViewModel.puml
!include .\\MVC\Models\AppUserHistroyViewModel.puml
!include .\\MVC\Models\AppUserPayOnlineViewModel.puml
!include .\\MVC\Models\FacultiesViewModel.puml
!include .\\MVC\Models\UserViewModel.puml
!include .\\MVC\Services\AccountService.puml
!include .\\MVC\Services\ConversionService.puml
!include .\\MVC\Services\GroupService.puml
!include .\\MVC\Services\TransactionHistoryService.puml
!include .\\MVC\Services\TransactionService.puml
!include .\\MVC\Services\UserGroupService.puml
!include .\\MVC\Services\UserService.puml
!include .\\WebAPI\Controllers\AccountsController.puml
!include .\\WebAPI\Controllers\ConversionsController.puml
!include .\\WebAPI\Controllers\GroupsController.puml
!include .\\WebAPI\Controllers\TransactionController.puml
!include .\\WebAPI\Controllers\TransactionHistoriesController.puml
!include .\\WebAPI\Controllers\UserGroupController.puml
!include .\\WebAPI\Controllers\UsersController.puml
!include .\\WebAPI\ExternalServices\PrinterSystemConnector.puml
!include .\\WebAPI\Mapper\AccountMapper.puml
!include .\\WebAPI\Mapper\ConversionMapper.puml
!include .\\WebAPI\Mapper\GroupMapper.puml
!include .\\WebAPI\Mapper\TransactionHistoryMapper.puml
!include .\\WebAPI\Mapper\UserGroupMapper.puml
!include .\\WebAPI\Mapper\UserMapper.puml
!include .\\MVC\Controllers\Admin\AccountsController.puml
!include .\\MVC\Controllers\Admin\ConversionsController.puml
!include .\\MVC\Controllers\Admin\GroupsController.puml
!include .\\MVC\Controllers\Admin\TransactionHistoriesController.puml
!include .\\MVC\Controllers\Admin\UserGroupsController.puml
!include .\\MVC\Controllers\Admin\UsersController.puml
!include .\\MVC\Controllers\Util\Class.puml
!include .\\MVC\Controllers\Util\ToastrUtil.puml
!include .\\MVC\Services\Interfaces\Class.puml
!include .\\MVC\Services\Interfaces\IAccountService.puml
!include .\\MVC\Services\Interfaces\IConversionService.puml
!include .\\MVC\Services\Interfaces\IGroupService.puml
!include .\\MVC\Services\Interfaces\ITransactionHistoryService.puml
!include .\\MVC\Services\Interfaces\ITransactionService.puml
!include .\\MVC\Services\Interfaces\IUserGroupService.puml
!include .\\MVC\Services\Interfaces\IUserService.puml
!include .\\MVC\Services\QuerySnippet\QuerySnippet.puml
!include .\\MVC\Services\QuerySnippet\StandardQuerySet.puml
!include .\\DAL\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\DAL\obj\Debug\net80\DAL.AssemblyInfo.puml
!include .\\DAL\obj\Debug\net80\DAL.GlobalUsings.g.puml
!include .\\DAL\obj\Release\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\DAL\obj\Release\net80\DAL.AssemblyInfo.puml
!include .\\DAL\obj\Release\net80\DAL.GlobalUsings.g.puml
!include .\\DTO\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\DTO\obj\Debug\net80\DTO.AssemblyInfo.puml
!include .\\DTO\obj\Debug\net80\DTO.GlobalUsings.g.puml
!include .\\DTO\obj\Release\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\DTO\obj\Release\net80\DTO.AssemblyInfo.puml
!include .\\DTO\obj\Release\net80\DTO.GlobalUsings.g.puml
!include .\\MVC\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MVC\obj\Debug\net80\MVC.AssemblyInfo.puml
!include .\\MVC\obj\Debug\net80\MVC.GlobalUsings.g.puml
!include .\\MVC\obj\Debug\net80\MVC.MvcApplicationPartsAssemblyInfo.puml
!include .\\MVC\obj\Debug\net80\MVC.RazorAssemblyInfo.puml
!include .\\MVC\obj\Release\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\MVC\obj\Release\net80\MVC.AssemblyInfo.puml
!include .\\MVC\obj\Release\net80\MVC.GlobalUsings.g.puml
!include .\\MVC\obj\Release\net80\MVC.MvcApplicationPartsAssemblyInfo.puml
!include .\\MVC\obj\Release\net80\MVC.RazorAssemblyInfo.puml
!include .\\WebAPI\obj\Debug\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\WebAPI\obj\Debug\net80\WebApi.AssemblyInfo.puml
!include .\\WebAPI\obj\Debug\net80\WebApi.GlobalUsings.g.puml
!include .\\WebAPI\obj\Debug\net80\WebApi.MvcApplicationPartsAssemblyInfo.puml
!include .\\WebAPI\obj\Release\net80\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\WebAPI\obj\Release\net80\WebApi.AssemblyInfo.puml
!include .\\WebAPI\obj\Release\net80\WebApi.GlobalUsings.g.puml
!include .\\WebAPI\obj\Release\net80\WebApi.MvcApplicationPartsAssemblyInfo.puml
@enduml
