@startuml
!include .\\Program.puml
!include .\\Controllers\AppUserController.puml
!include .\\Controllers\FacultiesController.puml
!include .\\Controllers\HomeController.puml
!include .\\Controllers\LoginController.puml
!include .\\Models\AppUserBuyViewModel.puml
!include .\\Models\AppUserHistroyViewModel.puml
!include .\\Models\AppUserPayOnlineViewModel.puml
!include .\\Models\FacultiesViewModel.puml
!include .\\Models\UserViewModel.puml
!include .\\Services\AccountService.puml
!include .\\Services\ConversionService.puml
!include .\\Services\GroupService.puml
!include .\\Services\TransactionHistoryService.puml
!include .\\Services\TransactionService.puml
!include .\\Services\UserGroupService.puml
!include .\\Services\UserService.puml
!include .\\Controllers\Admin\AccountsController.puml
!include .\\Controllers\Admin\ConversionsController.puml
!include .\\Controllers\Admin\GroupsController.puml
!include .\\Controllers\Admin\TransactionHistoriesController.puml
!include .\\Controllers\Admin\UserGroupsController.puml
!include .\\Controllers\Admin\UsersController.puml
!include .\\Controllers\Util\Class.puml
!include .\\Controllers\Util\ToastrUtil.puml
!include .\\Services\Interfaces\Class.puml
!include .\\Services\Interfaces\IAccountService.puml
!include .\\Services\Interfaces\IConversionService.puml
!include .\\Services\Interfaces\IGroupService.puml
!include .\\Services\Interfaces\ITransactionHistoryService.puml
!include .\\Services\Interfaces\ITransactionService.puml
!include .\\Services\Interfaces\IUserGroupService.puml
!include .\\Services\Interfaces\IUserService.puml
!include .\\Services\QuerySnippet\QuerySnippet.puml
!include .\\Services\QuerySnippet\StandardQuerySet.puml
!include .\\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0\MVC.AssemblyInfo.puml
!include .\\obj\Debug\net8.0\MVC.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0\MVC.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Debug\net8.0\MVC.RazorAssemblyInfo.puml
!include .\\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Release\net8.0\MVC.AssemblyInfo.puml
!include .\\obj\Release\net8.0\MVC.GlobalUsings.g.puml
!include .\\obj\Release\net8.0\MVC.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Release\net8.0\MVC.RazorAssemblyInfo.puml
@enduml
